#!/usr/bin/env bash
#
# Metasploit Database Setup Script
# This script initializes PostgreSQL database for Metasploit Framework
#
# Default credentials (CHANGE THESE FOR PRODUCTION):
#   Database: msf
#   Username: msf
#   Password: msf_password
#   Host: localhost
#   Port: 5432
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_info() {
    echo -e "${BLUE}[*]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[+]${NC} $1"
}

print_error() {
    echo -e "${RED}[!]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[~]${NC} $1"
}

# Default database configuration
DB_NAME="${MSF_DB_NAME:-msf}"
DB_USER="${MSF_DB_USER:-msf}"
DB_PASS="${MSF_DB_PASS:-msf_password}"
DB_HOST="${MSF_DB_HOST:-localhost}"
DB_PORT="${MSF_DB_PORT:-5432}"

echo ""
print_info "Metasploit Database Setup"
echo "=========================================="
echo ""
print_warning "Default credentials will be used. To customize, set environment variables:"
echo "  MSF_DB_NAME, MSF_DB_USER, MSF_DB_PASS, MSF_DB_HOST, MSF_DB_PORT"
echo ""
print_info "Database: $DB_NAME"
print_info "Username: $DB_USER"
print_info "Host: $DB_HOST:$DB_PORT"
echo ""

# Check if running as root (needed for PostgreSQL setup)
if [ "$EUID" -eq 0 ]; then
    print_warning "Running as root - this is fine for initial setup"
    SUDO=""
else
    SUDO="sudo"
fi

# Check if PostgreSQL is installed
if ! command -v psql &> /dev/null; then
    print_error "PostgreSQL is not installed. Please install it first:"
    print_error "  pacman -S --noconfirm postgresql"
    exit 1
fi

# Initialize PostgreSQL data directory if needed
if [ ! -d "/var/lib/postgres/data" ] || [ -z "$(ls -A /var/lib/postgres/data 2>/dev/null)" ]; then
    print_info "Initializing PostgreSQL data directory..."
    $SUDO -u postgres initdb -D /var/lib/postgres/data
    print_success "PostgreSQL data directory initialized"
fi

# Start PostgreSQL service
print_info "Starting PostgreSQL service..."
$SUDO systemctl start postgresql 2>/dev/null || {
    print_warning "Could not start via systemctl, trying manual start..."
    $SUDO -u postgres pg_ctl -D /var/lib/postgres/data -l /var/lib/postgres/logfile start || {
        print_error "Failed to start PostgreSQL"
        exit 1
    }
}
sleep 2

# Check if PostgreSQL is running
if $SUDO -u postgres psql -c '\q' 2>/dev/null; then
    print_success "PostgreSQL is running"
else
    print_error "PostgreSQL is not running. Please start it manually."
    exit 1
fi

# Create database user if it doesn't exist
print_info "Creating database user '$DB_USER'..."
$SUDO -u postgres psql -tc "SELECT 1 FROM pg_user WHERE usename = '$DB_USER'" | grep -q 1 && {
    print_warning "User '$DB_USER' already exists, skipping creation"
} || {
    $SUDO -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';"
    print_success "User '$DB_USER' created"
}

# Create database if it doesn't exist
print_info "Creating database '$DB_NAME'..."
$SUDO -u postgres psql -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME" && {
    print_warning "Database '$DB_NAME' already exists, skipping creation"
} || {
    $SUDO -u postgres psql -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;"
    print_success "Database '$DB_NAME' created"
}

# Grant privileges
print_info "Granting privileges to '$DB_USER'..."
$SUDO -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
$SUDO -u postgres psql -d "$DB_NAME" -c "GRANT ALL ON SCHEMA public TO $DB_USER;"
print_success "Privileges granted"

# Configure Metasploit to use the database
print_info "Configuring Metasploit database connection..."

# Create .msf4 directory if it doesn't exist
MSF_DIR="$HOME/.msf4"
if [ "$SUDO" != "" ]; then
    # If using sudo, configure for the actual user
    ACTUAL_USER="${SUDO_USER:-$USER}"
    MSF_DIR="/home/$ACTUAL_USER/.msf4"
fi

mkdir -p "$MSF_DIR"

# Create database.yml configuration
cat > "$MSF_DIR/database.yml" << EOF
# Metasploit Database Configuration
# Generated by setup-metasploit-db.sh
#
# To change credentials:
# 1. Update PostgreSQL: sudo -u postgres psql
#    ALTER USER $DB_USER WITH PASSWORD 'new_password';
# 2. Update this file with the new password
# 3. Restart msfconsole

production:
  adapter: postgresql
  database: $DB_NAME
  username: $DB_USER
  password: $DB_PASS
  host: $DB_HOST
  port: $DB_PORT
  pool: 5
  timeout: 5
EOF

print_success "Database configuration saved to $MSF_DIR/database.yml"

# Initialize Metasploit database
if command -v msfconsole &> /dev/null; then
    print_info "Initializing Metasploit database schema..."
    # Run msfconsole with db_status to initialize schema
    echo "db_status; exit" | msfconsole -q 2>&1 | grep -q "Connected to" && {
        print_success "Metasploit database initialized and connected"
    } || {
        print_warning "Metasploit database schema will be initialized on first msfconsole run"
    }
else
    print_warning "msfconsole not found. Database schema will be initialized when Metasploit is installed."
fi

echo ""
print_success "=========================================="
print_success "Metasploit Database Setup Complete!"
print_success "=========================================="
echo ""
print_info "Database Details:"
echo "  Database: $DB_NAME"
echo "  Username: $DB_USER"
echo "  Password: $DB_PASS"
echo "  Host: $DB_HOST:$DB_PORT"
echo ""
print_warning "SECURITY NOTE: Please change the default password!"
echo ""
print_info "To change the database password:"
echo "  1. Connect to PostgreSQL:"
echo "     sudo -u postgres psql"
echo "  2. Change the password:"
echo "     ALTER USER $DB_USER WITH PASSWORD 'your_new_password';"
echo "  3. Update the password in: $MSF_DIR/database.yml"
echo ""
print_info "To verify the connection, run:"
echo "  msfconsole -q -x 'db_status; exit'"
echo ""
